### ISSUE TITLE
Unable to retrieve NPSSO Token

### ISSUE THREAD

**Issue by CiRKuitService** [emi662002/PlayStationNetwork-issues#1]
I am unable to find any source to retrieve the NPSSO Token from PSN - is this deriving from the new signin-model for PSN or some other issue?

**Comment by emi662002** [comment]
Did you follow the steps as described in the community forum? Just
retrieved a new token, no issues.

Op wo 13 mrt. 2024 08:45 schreef CiRKuitService ***@***.***>:

**Comment by CiRKuitService** [comment]
Thank you for returning in this so quickly. 
I just did another run now, and this time it went through and all good.
